[package]
name = "nlp"
version = "0.1.0"
edition = "2021"

[lib]
name = "nlp"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.16.0"
ic-cdk-macros = "0.16.0"
candid = "0.10.10"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.17.1"