[package]
name = "network"
version = "0.1.0"
edition = "2021"

[lib]
name = "network"
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.10"
ic-cdk = "0.16"
ic-cdk-macros = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
